### ISSUE TITLE
Collect tokens from ArXiv LaTeX

### ISSUE THREAD

**Issue by rodneykinney** [allenai/OLMo#133]
RedPajama includes [data sourced from ArXiv](https://github.com/togethercomputer/RedPajama-Data/tree/main/data_prep/arxiv)

An alternative is [unArXive](https://github.com/IllDepence/unarXive)

S2's LaTex dumps from ArXiv are in `s3://ai2-s2-scholarphi-pipeline-prod/daq/arxiv-source-data/bymonth/`

@kyleclo @soldni

**Comment by dumitrac** [comment]
Marking the items prior to Feb 29th as "closed".
