### ISSUE TITLE
Try adding intermediate layer losses

### ISSUE THREAD

**Issue by epwalsh** [allenai/OLMo#196]
### 🚀 The feature, motivation and pitch

E.g. we have an LM loss at 1/2, 1/4, 1/8 of the model.

To avoid the degenerate scenario where, for example, the first half of the model does well but the 2nd half just becomes a bunch of ~identity layers, we could have a separate LM head for each loss, i.e. at each layer in the model where we apply an LM loss. So we'd have to untie the embedding matrix from the LM head.

**Comment by dumitrac** [comment]
Marking the items prior to Feb 29th as "closed".

**Comment by dumitrac** [comment]
Marking the items prior to Feb 29th as "closed".
