### ISSUE TITLE
Try new base image from Samuel Antao

### ISSUE THREAD

**Issue by epwalsh** [allenai/OLMo#214]
[`sfantao/pytorch-lumi:sles-rocm-5.5.1-python-3.10-pytorch-v2.0.1`](https://hub.docker.com/layers/sfantao/pytorch-lumi/sles-rocm-5.5.1-python-3.10-pytorch-v2.0.1/images/sha256-b571eff246ded0aa5df9286d7a064f62a8c124c5bd8e3bfc94b07758ed06646b?context=explore) (on Ducker hub).

**Comment by dumitrac** [comment]
Marking the items prior to Feb 29th as "closed".
