### ISSUE TITLE
PyTorch scaled_dot_product_attention doesn't support broadcast for grouped-query-attention

### ISSUE THREAD

**Issue by saurabh111233212** [allenai/OLMo#242]
### ❓ The question

I tried implementing [grouped query attention](https://arxiv.org/pdf/2305.13245.pdf) in [this pull request](https://github.com/allenai/LLM/pull/241), but seems that pytorch's `scaled_dot_product_attention` doesn't support the kind of broadcasting we'd need for this. Revisit if/when this gets fixed on pytorch's end.

**Comment by dumitrac** [comment]
I apologize for our delay in response. In order to help surface current, unresolved issues, we are closing tickets prior to February 29.
Please reopen your ticket if you are continuing to experience this issue.
Thank you!
