### ISSUE TITLE
Debugging the Spikyness of the 7B

### ISSUE THREAD

**Issue by epwalsh** [allenai/OLMo#288]
- [x] FP32 all reduce (see #289, #291). - @epwalsh 
 - [x] Check whether parameters and optimizer state really are fp32. Expectation: They are. - @epwalsh 
 - [ ] Check on Alibi bias in fp32? Should be fp32, not bf16. Have to ablate perf with this (#289). - @ananyahjha93 
 - [x] Check why parameter norms in the graphs start at the same point even though the init is different. - @ibeltagy 
 - [ ] Run on other data (just Wikipedia)
 - [ ] Small model. 8M? 350M? 760M? 1B? Does it still spike?
   - [ ] Keep batch size same
   - [ ] "OPT formula for scale". What does that mean?
   - [ ] Same LR
 - [ ] Write some checks to make make sure bf16 values are roughly within the right range

**Comment by dumitrac** [comment]
Marking the items prior to Feb 29th as "closed".
