### ISSUE TITLE
Revisit Z-loss

### ISSUE THREAD

**Issue by epwalsh** [allenai/OLMo#361]
## Update - 11/3/23

Mitch is a big fan of Z-loss. Currently they're running Z-loss, no weight tying, LR=1e-3, wd=0.1, QK norm. So with Z-loss (and potentially QK norm) it seems you can get away with a higher LR. Mitch also believes Z-loss helps avoid slow divergence late in  training.

**Comment by dumitrac** [comment]
Marking the items prior to Feb 29th as "closed".
