### ISSUE TITLE
FSDP Overlap Investigation

### ISSUE THREAD

**Issue by 2015aroras** [allenai/OLMo#386]
The problem is that on LUMI, FSDP doesn't overlap computation and communication like it should. Evidence comes from this profiler trace:

![Image](https://github.com/allenai/LLM/assets/920638/9d5d4437-adc7-485d-97c3-4cf71643808f)

It may be noteworthy that the NCCL GPU stream does not have an ID:

![Image](https://github.com/allenai/LLM/assets/920638/07ea5684-1f05-42f4-a027-a26591ccbe2a)

The problem persists on LUMI with torch 2.0.1, torch 2.1, and torch-nightly (to be torch 2.2) on 24 nodes.

There is no problem on a single 4x A100 node in Cirrascale.

Problem is also visible on a single AMD node in AAC.

**Comment by garrett361** [comment]
@2015aroras @dirkgr great thread! Is there any update you could provide on this issue? Did you trace it back to something in the AMD stack?

**Comment by dumitrac** [comment]
Marking the items prior to Feb 29th as "closed".
