### ISSUE TITLE
Update the OLMo torch dependencies in pyproject.toml from "torch>=2.0,<2.2" to "torch>=2.0,<2.3".

### ISSUE THREAD

**Issue by anw90** [allenai/OLMo#432]
### 🚀 The feature, motivation and pitch

I have tested OLMo on Torch 2.2.0, and everything works fine. Can we update the Torch version requirements from <2.2 to <2.3?

**Comment by epwalsh** [comment]
Hey @anw90 there's one piece of our training code that breaks with torch 2.2.0 (our `LocalCheckpointer`, which relies on a PyTorch internal FSDP API, so is fairly brittle). That code needs to be updated to accommodate 2.2.0 before we can relax the requirement.

**Comment by anw90** [comment]
Okay, Got it. Thanks @epwalsh.
