### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by DouPiChen** [allenai/OLMo#438]
### ❓ The question

When I run ``` torchrun --nproc_per_node=4 scripts/train.py configs/official/OLMo-1B.yaml ```, I get the ConnectionRefusedError as follows
<img width="641" alt="2024-02-07 095742" src="https://github.com/allenai/OLMo/assets/76193441/e9ed7461-67c1-44d6-8d77-e09decd2936e">
<img width="916" alt="2024-02-07 095827" src="https://github.com/allenai/OLMo/assets/76193441/f8a3b138-431c-4f92-9ad1-01751dac7603">

I have changed url in OLMo-1B.yaml as 
<img width="620" alt="2024-02-07 100159" src="https://github.com/allenai/OLMo/assets/76193441/97dc9b79-505b-4fce-b560-4c29716cc0d9">

**Comment by 2015aroras** [comment]
It's hard to tell what the error is from jus the call stack, which is almost all inside python's `urllib3` error. Based on the last INFO line in the first image, the error appears to be in the [Weights & Biases](https://wandb.ai/home) SDK. If you do not need Weights & Biases to keep track of run metrics, you can set `--wandb` to `null`. That is, run `torchrun --nproc_per_node=4 scripts/train.py configs/official/OLMo-1B.yaml --wandb=null`.

**Comment by dumitrac** [comment]
I apologize for our delay in response. In order to help surface current, unresolved issues, we are closing tickets prior to February 29.
Please reopen your ticket if you are continuing to experience this issue.
Thank you!
