### ISSUE TITLE
Integration with langchain

### ISSUE THREAD

**Issue by JeisonJimenezA** [allenai/OLMo#439]
### ❓ The question

Hello, congratulations on your excellent work with OLMo.

 Are you planning to integrate OLMo into frameworks like Langchain that could enhance the possibilities of the model, with the inclusion of agents among many more options.

**Comment by dirkgr** [comment]
We are planning on integrating it properly with Huggingface transformers. A lot of integrations come automatically once we do that. I don't know if langchain is among those.

FWIW, it's already quite easy to run the OLMo models in Huggingface transformers. All you have to do is install this repo and `import olmo_hf`.
