### ISSUE TITLE
Why does config/llama7.yaml not use OlmoLlamaBlock?

### ISSUE THREAD

**Issue by gahdritz** [allenai/OLMo#444]
A sample "LLaMA-like" config is provided, but it doesn't use the OlmoLlamaBlock BlockType defined in `model/olmo.py`. Why is that?

https://github.com/allenai/OLMo/blob/97296e610c24dd1bb098ec64660dfcafcba62d24/configs/llama7.yaml#L21

**Comment by 2015aroras** [comment]
The remaining changes to make that config more Llama-like in behavior are in https://github.com/allenai/OLMo/pull/358. I don't remember why we didn't merge that change, but the throughput was very poor due to how our implementation tried to get identical results in the attention mechanism.

**Comment by dumitrac** [comment]
I apologize for our delay in response. In order to help surface current, unresolved issues, we are closing tickets prior to February 29.
Please reopen your ticket if you are continuing to experience this issue.
Thank you!
