### ISSUE TITLE
Minimum GPU memory requirement

### ISSUE THREAD

**Issue by 0novanta** [allenai/OLMo#452]
### ❓ The question

I am currently trying to fine-tune OLMo-1B on a GeForce GTX 1080 Ti with 12GB of dedicated memory but it crashes because it needs more memory.

Which is the minimum GPU-dedicated memory requirement in order to perform fine-tuning on OLMo-1B?
Are there any configuration parameters that can improve performance memory-wise?

**Comment by natolambert** [comment]
Hey! Are you loading a quantized model? As a rule of thumb for fp16, a model will need ~2x the N Billion parameters to run inference (here 2GB), for fine-tuning it's more complex.

An example text I've written before is:
> For fine-tuning, the equation is more complex. Without memory-efficient methods such as QLoRA, it would normally take multiple consumer GPUs or a top-end GPU (H100, A100, etc) to fine-tune the model. During training, the model weights, gradients, and optimizer weights need to be stored per parameter, which ends up being approximately 70GB of VRAM for a 7B model.

So I think it should be close for a 1B model, but maybe try something like [peft](https://github.com/huggingface/peft)

**Comment by natolambert** [comment]
Here's another good resource https://huggingface.co/spaces/hf-accelerate/model-memory-usage

**Comment by 0novanta** [comment]
UPDATE:
I managed to build a peft model with the following lines:
```
peft_config = LoraConfig(
    inference_mode=False, 
    r=8, 
    lora_alpha=32, 
    lora_dropout=0.1,
    target_modules=["blocks.0.attn_out"] # as a starting example
)
olmo_model = Olmo(cfg.model)
olmo_model.config_to_dict()
olmo_model = get_peft_model(olmo_model, peft_config)
```
where `.config_to_dict()` was necessary because peft accesses fields as `['field']` rather than `.field`.
Then, the number of trainable parameters returned by `olmo_model.print_trainable_parameters()` is:
```
trainable params: 32,768 || all params: 1,176,797,184 || trainable%: 0.002784507003035113
```
However, the CUDA out of memory error persists:
```
torch.cuda.OutOfMemoryError: CUDA out of memory. 
Tried to allocate 128.00 MiB. GPU 0 has a total capacty of 10.91 GiB of which 69.25 MiB is free. 
Including non-PyTorch memory, this process has 10.81 GiB memory in use. 
Of the allocated memory 10.14 GiB is allocated by PyTorch, and 5.95 MiB is reserved by PyTorch but unallocated. 
If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  
See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
As of now, the `load_path` parameter in the configuration file is set to `null` since I do not know how to properly download a checkpoint from huggingface and generate all the relevant `.pt` files. More generally, I do not understand where the models are loaded from. Are they loaded from `~/.cache/huggingface/hub/models--allenai--OLMo-1B/refs` ?

It would be interesting to try on a quantized model.

**Comment by 0novanta** [comment]
> Here's another good resource https://huggingface.co/spaces/hf-accelerate/model-memory-usage

It does not seem to find neither OLMo-1B or OLMo-7B.

**Comment by natolambert** [comment]
Ah the tool needs custom code / we're working on making it work in Transformers be default @0novanta , sorry it was misleading for now.

**Comment by natolambert** [comment]
For quanitizing, I recommend checking out the peft docs / open an issue there.

**Comment by 0novanta** [comment]
Thank you for the feedback @natolambert !

I was unclear in my comment. I am not sure I'm loading the correct model when fine-tuning.
I understand the checkpoint path must be specified via the `load_path` parameter in the configuration file `config.yaml`. However, I do not understand how to download correctly a checkpoint to use for fine-tuning.

What I do is run this Python line:
```
olmo = AutoModelForCausalLM.from_pretrained("allenai/OLMo-1B", revision='step20000-tokens84B')
```
which downloads something in `~/.cache/huggingface/hub/models--allenai--OLMo-1B/refs`, however if I try to make `load_path` point to that folder I am unable to run the script for fine-tuning (it crashes because some `.pt` files are missing).

What I did in order to get to the CUDA out of memory error was to set `load_path` to `null` which (if I understand correctly) should make the script use the latest version available.

So my question is, how do I download a checkpoint correctly in order to perform fine-tuning?

If I need to open a new issue please tell me and I will.

**Comment by natolambert** [comment]
Yeah feel free to reopen that issue. I think you may need the `-unsharded` arg.
Please provide more details there.
