### ISSUE TITLE
Fine-tuning starting from a checkpoint

### ISSUE THREAD

**Issue by 0novanta** [allenai/OLMo#454]
### ❓ The question

I would like to fine-tune OLMo-1B starting from one of its checkpoints with my data.
I understand that there are three steps in order to accomplish this task:

1. tokenization of my data
2. checkpoint download
3. configuring a custom configuration file such as `OLMo-1B-fine-tuning.yaml`

I followed the instructions provided in the [Fine-tuning](https://github.com/allenai/OLMo?tab=readme-ov-file#fine-tuning) paragraph of the `README.md`.
I successfully tokenized my data taking as an example `scripts/prepare_tulu_data.py`.
Then I modified the `.yaml` file as suggested by the following command:
```
torchrun --nproc_per_node=8 scripts/train.py {path_to_train_config} \
    --data.paths=[{path_to_data}/input_ids.npy] \
    --data.label_mask_paths=[{path_to_data}/label_mask.npy] \
    --load_path={path_to_checkpoint} \
    --reset_trainer_state
```
The point that I am missing is the how to correctly download a checkpoint.
I found all the available OLMo-1B checkpoints listed in the [revisions.txt](https://huggingface.co/allenai/OLMo-1B/blob/main/revisions.txt) file. 
I tried to download a model using huggingface library as follows:
```
olmo = AutoModelForCausalLM.from_pretrained("allenai/OLMo-1B", revision='step20000-tokens84B')
```
targeting checkpoint `step20000-tokens84B`. 
This command actually saves some data in `~/.cache/huggingface/hub/models--allenai--OLMo-1B`, however providing any file in any of its subfolders as datum for `load_path` parameter results in the `train.py` script crashing due to the lack of some `.pt` files with the following error message (in the case I provide subfolder `refs`):
```
FileNotFoundError: file /my/home/.cache/huggingface/hub/models--allenai--OLMo-1B/refs/step20000-tokens84B/rank0.pt not found
```

My question is: how do I download correctly an OLMo-1B checkpoint and how do I set it up in order to load it via the `load_path` parameter?

**Comment by dumitrac** [comment]
I apologize for our delay in response. In order to help surface current, unresolved issues, we are closing tickets prior to February 29.
Please reopen your ticket if you are continuing to experience this issue.
Thank you!
