### ISSUE TITLE
Full OLMo checkpoints?

### ISSUE THREAD

**Issue by jiahai-feng** [allenai/OLMo#467]
### 🚀 The feature, motivation and pitch

Hi, really appreciate the work that y'all are doing.

Are y'all planning to release the checkpoint files for OLMo 7B? Right now the HF checkpoints don't seem to contain enough information to do finetuning using this repo. For e.g., optimizer states and config files are missing.

**Comment by epwalsh** [comment]
Hi @jiahai-feng, yes we are. @2015aroras do you know the status of this?

**Comment by epwalsh** [comment]
https://github.com/allenai/OLMo/pull/500
