### ISSUE TITLE
Did OLMo train its own tokenizer? 

### ISSUE THREAD

**Issue by amulil** [allenai/OLMo#470]
### 📚 The doc issue

I look the video [Let's build the GPT Tokenizer](https://www.youtube.com/watch?v=zduSFxRajkE). I feel it's cool to train a own tokenizer. And I have a question, Did OLMo train its own tokenizer?

**Comment by epwalsh** [comment]
Hey @amulil, we initially considered training our own, and actually created several prototype tokenizers from scratch, but ultimately we decided to start from the GPT-NeoX tokenizer to reduce risk.

**Comment by soldni** [comment]
Hi @aflah02! 

Those tokens are used for PII masking; the [Dolma paper](https://arxiv.org/pdf/2402.00159) provides details on how we implemented it in the first version of Dolma:

![Screenshot 2024-11-06 at 09 49 28](https://github.com/user-attachments/assets/55faf7f0-aef1-4b57-8b35-0c207555f5bc)

While models like [OLMoE](https://huggingface.co/datasets/allenai/OLMoE-mix-0924) are trained on data that is not masked the same way, we plan to keep these special tokens in for backwards compatibility reasons.

**Comment by aflah02** [comment]
Hi @soldni 

Thanks for sharing this!
