### ISSUE TITLE
Why is OLMo not integrated into Transformers?

### ISSUE THREAD

**Issue by clintg6** [allenai/OLMo#472]
### ❓ The question

I was surprised when I looked at https://github.com/huggingface/transformers/tree/main/src/transformers/models and didn't see any modules for OLMo. Why is  OLMo not integrated with transformers directly and is there a plan for integration?

**Comment by ianand** [comment]
https://github.com/allenai/OLMo/issues/439#issuecomment-1965547126

**Comment by dirkgr** [comment]
OLMo is now properly integrated with Transformers!
