### ISSUE TITLE
I'm interested in OLMo-twin, but I found no more information except its name.

### ISSUE THREAD

**Issue by HuXinjing** [allenai/OLMo#479]
### ❓ The question

So, where do i find more information about OLMo-twin, such as its backbone.

**Comment by AkshitaB** [comment]
@HuXinjing Both the OLMo-7B and OLMo-7B-Twin-2T have the same architecture, and have been trained from scratch on the same data. You can find the model here: https://huggingface.co/allenai/OLMo-7B-Twin-2T

**Comment by HuXinjing** [comment]
That's to say "twin" here means it is the sibling of OLMo-7b? I misunderstood it.&nbsp;

---Original---
From: "Akshita ***@***.***&gt;
Date: Tue, Mar 5, 2024 06:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [allenai/OLMo] I'm interested in OLMo-twin, but I found no moreinformation except its name. (Issue #479)




 
@HuXinjing Both the OLMo-7B and OLMo-7B-Twin-2T have the same architecture, and have been trained from scratch on the same data. You can find the model here: https://huggingface.co/allenai/OLMo-7B-Twin-2T

**Comment by dumitrac** [comment]
@HuXinjing - correct, same models, except for the hardware they're trained on: Twin is trained on LUMI (AMD) while the non-twin is on Mosaic (NVIDIA).
Please reopen this if you have followup questions.
