### ISSUE TITLE
How can I finetune Olmo-7B using this repo?

### ISSUE THREAD

**Issue by rajasekharmekala** [allenai/OLMo#499]
### ❓ The question

Hi @epwalsh, @2015aroras

I am trying to setup finetuning for OLMo-7B  from huggingface model, but seems like that might not be possible, as the checkpoint requires trainer and optimizer states e.t.c.

Is it possible to use this repo for finetuning from the public checkpoint? or if I can download the checkpoint that is compatible with this repo?

Thanks.

**Comment by epwalsh** [comment]
Hey @rajasekharmekala, see: https://github.com/allenai/OLMo/pull/500.

**Comment by rajasekharmekala** [comment]
Thanks @epwalsh and @2015aroras. I was able to load the model from the checkpoints in #500
