### ISSUE TITLE
Training on a single GPU

### ISSUE THREAD

**Issue by ShenZhen0502** [allenai/OLMo#502]
### ❓ The question

I'm interested in learning OLMO on my personal computer. Can I use the train_tiny configuration file to train it on a single GPU, so that I can quickly learn the code through debugging?

**Comment by 2015aroras** [comment]
Sure, I don't see why it wouldn't work.

As an aside, depending on the RAM of the GPU you could run the 1B (or maybe even the 7B) on a single GPU.

**Comment by dumitrac** [comment]
@ShenZhen0502 - please reopen this item or a new one if you have further questions.
