### ISSUE TITLE
could some one help  why the tokens begin with G.

### ISSUE THREAD

**Issue by oras903** [allenai/OLMo#505]
### ❓ The question

  Hi,   I try to run the tutorials and want to see the  original tokens，and then the  result is  like this ,  is that's wrong ?

![image](https://github.com/allenai/OLMo/assets/24708057/4ecaae30-3f31-46d8-b584-1fded9530e16)

**Comment by ianand** [comment]
GPT2 tokenizer has a similar same setup where Ġ is used as the space character. See https://github.com/openai/gpt-2/issues/80 and https://discuss.huggingface.co/t/bpe-tokenizers-and-spaces-before-words/475/2

**Comment by natolambert** [comment]
Yeah this is expected. Some will start with `_` (sentencepiece tokenizers)
