### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'cache_position'

### ISSUE THREAD

**Issue by sanderland** [allenai/OLMo#525]
### 🐛 Describe the bug

When using generate, the above error is raised. In the source I can indeed see that forward() does not take such an argument or ignore unexpected extra args.

### Versions

Python 3.9.2
ai2-olmo==0.2.5
transformers==4.39.1
torch==2.2.1
(etc)

**Comment by Ronho** [comment]
Hi! I experienced this issue as well. As I am not familiar with anything of this, please take my words with a grain of salt.

Debugging this showed that `cache_position` is passed to `prepare_inputs_for_generation` as part of the kwargs. The `cache_position` has been added to the model_kwargs in this [commit](https://github.com/huggingface/transformers/commit/23db187d9223cfbd535a3a76fb518ca2c1429633#diff-26783ca033d92b4ce2e01eb691dbf5b05dd972b0cbfdc69fc726cf77a9dcb011R1940).

Adding `cache_position` to the forward method of `OLMoForCausalLM` does the trick but I am not sure how it is inteded to work/be used.

**Comment by fkcoder** [comment]
`transformers==4.38.2` works for me.

**Comment by Ronho** [comment]
Yes, it should - the mentioned commit was added in version 4.39.0.

**Comment by 2015aroras** [comment]
@Ronho is spot on with the cause and version. I didn't see this issue but I fixed this in https://github.com/allenai/OLMo/pull/534
