### ISSUE TITLE
Flash Attention for AMD GPUs

### ISSUE THREAD

**Issue by prakamya-mishra** [allenai/OLMo#539]
### ❓ The question

Hi,

In the official OLMo-1B.yaml config file, I see that the flash attention is not available for AMD GPUs:

> Line 17: flash_attention: false  # not available on AMD

Can you suggest a way OLMo can be run with flash attention on the AMD GPUs?

When I enable the tag here, although there is a slight increase in the throughput, the training diverges quickly.
<img width="215" alt="olmo loss wandb" src="https://github.com/allenai/OLMo/assets/22093105/8f0e2d70-d989-45c0-8ad3-0d0bf121dca6">
<img width="217" alt="olmo throughput" src="https://github.com/allenai/OLMo/assets/22093105/4b097df9-a60a-4bd4-afde-c2a15a0508db">

It would be great if someone can point on the right way to run OLMo training with Flash Attention on AMD GPUs.

Thanks!

**Comment by prakamya-mishra** [comment]
@dirkgr @schmmd did you also face similar issue in your experiments?

**Comment by dirkgr** [comment]
We did also face this issue. This is why flash attention is disabled by default on OLMo.

**Comment by prakamya-mishra** [comment]
Thank you for answering.
