### ISSUE TITLE
SFT and DPO Finetuning Code Available?

### ISSUE THREAD

**Issue by YilunZhou** [allenai/OLMo#545]
### ❓ The question

Does the repository contain the code to train the SFT and Instruct model variants? If so, could anyone point me to it?

**Comment by 2015aroras** [comment]
I think the instructions for training the SFT and Instruct model are covered in the `Fine-tuning` section of the README, and essentially boil down to changing the dataset on which you train (starting from a pre-trained checkpoint). @hamishivi Please correct me if I'm wrong, and can you share what datasets were used for creating the SFT and instruct variants?

**Comment by hamishivi** [comment]
Hi, yeah the readme has details. We used the Tulu dataset to train the SFT version, matching the script (here)[https://github.com/allenai/OLMo/blob/main/scripts/prepare_tulu_data.py]. 

For instruct, we also applied DPO using [open-instruct](https://github.com/allenai/open-instruct/tree/main) - please see the readme there for details. You can also do SFT training with open-instruct too, if you prefer.

The datasets can be found here:
- https://huggingface.co/datasets/allenai/tulu-v2-sft-mixture
- https://huggingface.co/datasets/argilla/ultrafeedback-binarized-preferences-cleaned (for DPO)

**Comment by YilunZhou** [comment]
Thanks both for your help!
