### ISSUE TITLE
Gradient Checkpointing

### ISSUE THREAD

**Issue by fakerybakery** [allenai/OLMo#549]
Hi, I'm trying to finetune OLMo but running into the error `ValueError: OLMoForCausalLM does not support gradient checkpointing.` Is this planned in the future?

Thanks for releasing OLMo!

**Comment by 2015aroras** [comment]
We just released OLMo integration into the transformers library (v4.40.0 and up), with corresponding `-hf` checkpoints on Huggingface Hub (e.g. https://huggingface.co/allenai/OLMo-1.7-7B-hf). I haven't tried gradient checkpointing there, but it may work.

**Comment by bdytx5** [comment]
I confirmed it does not work. This would a great addition.

**Comment by dirkgr** [comment]
I am pretty sure this works now, since the way our HF model works is now completely different. Please re-open if that is not the case.
