### ISSUE TITLE
Flash attention 2.0 support

### ISSUE THREAD

**Issue by johnhalloran321** [allenai/OLMo#557]
### 🚀 The feature, motivation and pitch

```
from transformers import AutoModelForCausalLM
import torch
model = AutoModelForCausalLM.from_pretrained("allenai/OLMo-1B", revision = "step30000-tokens126B", 
                                             use_flash_attention_2="flash_attention_2",
                                             torch_dtype = torch.bfloat16,
                                             trust_remote_code=True)
```

Results in:
`ValueError: OLMoForCausalLM does not support Flash Attention 2.0 yet. Please request to add support where the model is hosted, on its model hub page: https://huggingface.co/allenai/OLMo-1B/discussions/new or in the Transformers GitHub repo: https://github.com/huggingface/transformers/issues/new`

Could support for flash attention 2.0 be added to the OLMo-1B/7B?

**Comment by dumitrac** [comment]
@johnhalloran321, could you please remove the "use_flash_attention_2" argument, and instead add "flash_attention=True".
With this, the error went away on my end.
Please let me know if that resolved it.

**Comment by johnhalloran321** [comment]
Hi dumitrac, 

Thanks for the quick response, that looks to have fixed things.  Closing the issue.

Best
