### ISSUE TITLE
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

### ISSUE THREAD

**Issue by mclanza** [allenai/OLMo#581]
### 🐛 Describe the bug

Following instructions here  https://github.com/allenai/OLMo  used to work some days ago. I tried it yesterday and today again and it throws the following warning/error
`You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.`
and no results are shown as it used to show.

This is the code that I'm trying to run

```
from hf_olmo import * # registers the Auto* classes

from transformers import AutoModelForCausalLM, AutoTokenizer

olmo = AutoModelForCausalLM.from_pretrained("allenai/OLMo-7B")
tokenizer = AutoTokenizer.from_pretrained("allenai/OLMo-7B")

message = ["Language modeling is "]
inputs = tokenizer(message, return_tensors='pt', return_token_type_ids=False)
response = olmo.generate(**inputs, max_new_tokens=100, do_sample=True, top_k=50, top_p=0.95)
print(tokenizer.batch_decode(response, skip_special_tokens=True)[0])
```

I also tried with `tokenizer = AutoTokenizer.from_pretrained("allenai/OLMo-7B",  trust_remote_code=True)` but same message is shown.

I also tried `allenai/olmo-7b` (lowercase) and same message is shown.

What am I missing? What could have changed since the last time that it worked?

Thanks!

### Versions

python --version && pip freeze                      
Python 3.9.6
ai2-olmo==0.3.0
antlr4-python3-runtime==4.9.3
boto3==1.34.107
botocore==1.34.107
cached_path==1.6.2
cachetools==5.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
filelock==3.13.4
fsspec==2024.5.0
google-api-core==2.19.0
google-auth==2.29.0
google-cloud-core==2.4.1
google-cloud-storage==2.16.0
google-crc32c==1.5.0
google-resumable-media==2.7.0
googleapis-common-protos==1.63.0
huggingface-hub==0.21.4
idna==3.7
Jinja2==3.1.4
jmespath==1.0.1
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.4
omegaconf==2.3.0
packaging==24.0
pillow==10.3.0
proto-plus==1.23.0
protobuf==4.25.3
pyasn1==0.6.0
pyasn1_modules==0.4.0
Pygments==2.18.0
python-dateutil==2.9.0.post0
PyYAML==6.0.1
regex==2024.5.15
requests==2.31.0
rich==13.7.1
rsa==4.9
s3transfer==0.10.1
safetensors==0.4.3
six==1.16.0
sympy==1.12
tokenizers==0.19.1
torch==2.0.0
torchaudio==2.0.1
torchvision==0.15.1
tqdm==4.66.4
transformers==4.40.2
typing_extensions==4.11.0
urllib3==1.26.18

**Comment by 2015aroras** [comment]
Hi Marie,

We integrated OLMo directly into the `transformers` library recently, which caused us to change the checkpoints to use. You will probably want to use `allenai/OLMo-7B-hf` instead, or `allenai/OLMo-1.7-7B-hf` if you would like to use our recently-released improved 7B model. I have updated the README with the new information: https://github.com/allenai/OLMo/pull/589. Sorry for the inconvenience.

**Comment by mclanza** [comment]
Thanks @2015aroras !

I tried it with the following code 

```
from transformers import AutoModelForCausalLM, AutoTokenizer

olmo = AutoModelForCausalLM.from_pretrained("allenai/OLMo-1.7-7B-hf")
tokenizer = AutoTokenizer.from_pretrained("allenai/OLMo-1.7-7B-hf", trust_remote_code=True)

message = ["Language modeling is "]
inputs = tokenizer(message, return_tensors='pt', return_token_type_ids=False)
response = olmo.generate(**inputs, max_new_tokens=100, do_sample=True, top_k=50, top_p=0.95)
print(tokenizer.batch_decode(response, skip_special_tokens=True)[0])
```

and it hangs after loading checkpoint shards

![image](https://github.com/allenai/OLMo/assets/22294835/0c90cbcd-002b-4769-aa22-3dde7d5fc9f5)

I tried it myself and some colleagues tried it too, on different machines, different environments and different networks. Any idea that could help us?

Thanks!

----
### Versions 
python --version && pip freeze                                                                                        
Python 3.9.6
ai2-olmo==0.3.0
antlr4-python3-runtime==4.9.3
boto3==1.34.111
botocore==1.34.111
cached_path==1.6.2
cachetools==5.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
filelock==3.13.4
fsspec==2024.5.0
google-api-core==2.19.0
google-auth==2.29.0
google-cloud-core==2.4.1
google-cloud-storage==2.16.0
google-crc32c==1.5.0
google-resumable-media==2.7.0
googleapis-common-protos==1.63.0
huggingface-hub==0.21.4
idna==3.7
Jinja2==3.1.4
jmespath==1.0.1
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.4
omegaconf==2.3.0
packaging==24.0
pillow==10.3.0
proto-plus==1.23.0
protobuf==4.25.3
pyasn1==0.6.0
pyasn1_modules==0.4.0
Pygments==2.18.0
python-dateutil==2.9.0.post0
PyYAML==6.0.1
regex==2024.5.15
requests==2.32.2
rich==13.7.1
rsa==4.9
s3transfer==0.10.1
safetensors==0.4.3
six==1.16.0
sympy==1.12
tokenizers==0.19.1
torch==2.2.2
torchaudio==2.2.2
torchvision==0.17.2
tqdm==4.66.4
transformers==4.40.2
typing_extensions==4.11.0
urllib3==1.26.18

**Comment by mclanza** [comment]
It hangs here:
`response = olmo.generate(**inputs, max_new_tokens=100, do_sample=True, top_k=50, top_p=0.95)`

----
Code:
```
from transformers import AutoModelForCausalLM, AutoTokenizer

print('Step 1...')
olmo = AutoModelForCausalLM.from_pretrained("allenai/OLMo-1.7-7B-hf")

print('Step 2...')
tokenizer = AutoTokenizer.from_pretrained("allenai/OLMo-1.7-7B-hf")

message = ["Language modeling is "]
print('Step 3...')
inputs = tokenizer(message, return_tensors='pt', return_token_type_ids=False)

print('Step 4...')
response = olmo.generate(**inputs, max_new_tokens=100, do_sample=True, top_k=50, top_p=0.95)

print('Step 5...')
print(tokenizer.batch_decode(response, skip_special_tokens=True)[0])
```

Result:
<img width="1578" alt="image" src="https://github.com/allenai/OLMo/assets/22294835/637035b6-d26e-469b-ab10-e4d32691491d">

**Comment by mclanza** [comment]
It took much more time (hours) but it finally worked. Any hint about that? Thanks!

<img width="1574" alt="image" src="https://github.com/allenai/OLMo/assets/22294835/f414aed9-4774-4320-89c4-f512604dd5de">

**Comment by mclanza** [comment]
Thanks for the detailed replies. It worked ok now. I'm closing the issue. Thanks again!
