### ISSUE TITLE
Expose memmap_dtype in the data configuration

### ISSUE THREAD

**Issue by leon-g-xu** [allenai/OLMo#595]
### 🚀 The feature, motivation and pitch

Can we request to add this feature in the OLMo framework?
We'd like to expose the `memmap_dtype` as a config in data configuration section.
Currently the framework always assumes that the memmap_dtype is `np.uint16`. In our run we actually need to use `np.uint32`.
Here's the PR to expose this config: https://github.com/allenai/OLMo/pull/594

**Comment by leon-g-xu** [comment]
Is there a process on how I can contribute back to the code? 
How do I get my PR reviewed?

**Comment by 2015aroras** [comment]
Fixed in #594
