### ISSUE TITLE
Finetuning config file

### ISSUE THREAD

**Issue by joellliu** [allenai/OLMo#609]
### ❓ The question

Hi, I am wondering if you can provide your config file for finetuning on the Tulu V2 dataset? It would be helpful for reproducing the finetuning results. In addition, have you tried SFT on the 1B model? How's the result? Thank you!

**Comment by 2015aroras** [comment]
Have you looked at https://github.com/allenai/open-instruct? It might have what you're looking for.

**Comment by joellliu** [comment]
> Have you looked at https://github.com/allenai/open-instruct? It might have what you're looking for.

Thanks for your reply! It seems the open-instruct repo is mainly for DPO. I wonder if you can provide the supervised finetuning config for training on the Tuluv2 dataset. Thank you!

**Comment by 2015aroras** [comment]
@hamishivi You probably know more about this?

**Comment by ethanlshen** [comment]
Hi! I have the same question and am wondering if there have been any updates on this? Thanks!

**Comment by hamishivi** [comment]
Hi, you can find the OLMo 2 SFT and DPO configs here: https://github.com/allenai/open-instruct/tree/main/configs/train_configs/olmo2

We do SFT and DPO in open-instruct (and RLVR).
