### ISSUE TITLE
What is the true MLP ratio for OLMo 7B?

### ISSUE THREAD

**Issue by jeqcho** [allenai/OLMo#625]
Hi,

In the [paper](https://arxiv.org/abs/2402.00838), a `mlp_ratio` of ~8/3 is reported for the OLMo 7B model.

![paper-table](https://github.com/allenai/OLMo/assets/42904912/a6dcd19c-b450-4230-bb64-6ca5b9b40e67)

However, in the configuration file, the d_model is listed as 4096, and the mlp_hidden_size is 22016. This results in a mlp_ratio of 22016/4096=5.375, which significantly differs from the reported 8/3 (approximately 2.67).

Here is the relevant section of the configuration file:
https://github.com/allenai/OLMo/blob/ddc884712e991608b69f7f6c04f464d5304f19d3/configs/official/OLMo-7B.yaml#L10-L14

Additionally, it is mentioned here that `mlp_hidden_size = mlp_ratio * d_model`:
https://github.com/allenai/OLMo/blob/ddc884712e991608b69f7f6c04f464d5304f19d3/olmo/config.py#L262-L271

**Comment by 2015aroras** [comment]
Our `mlp_hidden_size` is multiplied by a constant that depends on the activation function: 

https://github.com/allenai/OLMo/blob/2417b1176480e3b0d72ac225c558400862fc4c81/olmo/model.py#L451-L456

Our SwiGLU activation uses 0.5, and so our hidden size is halved. As a result, MLP ratio `22016/4096/2=2.6875≈8/3`.

**Comment by jeqcho** [comment]
Thanks for the clarification!
