### ISSUE TITLE
Key 'https://olmo_checkpoints' not in 'TrainConfig'

### ISSUE THREAD

**Issue by jeqcho** [allenai/OLMo#627]
### 📚 The doc issue

Hi,

Running the command below from the README returns an error

https://github.com/allenai/OLMo/blob/d72a262645d831cc80d4a974718598998103075f/README.md?plain=1#L129-L134

The error is 
```
OLMoConfigurationError: Key 'https://olmo_checkpoints' not in 'TrainConfig'
    full_key: https://olmo_checkpoints
    object_type=TrainConfig
```

It turns out that `clean_opt` is called on the command-line arguments

https://github.com/allenai/OLMo/blob/d72a262645d831cc80d4a974718598998103075f/scripts/train.py#L322-L344

`clean_opt` adds `=True` to `--load_path`, rendering the argument that follows as a flag too

https://github.com/allenai/OLMo/blob/d72a262645d831cc80d4a974718598998103075f/olmo/util.py#L214-L219

### Suggest a potential alternative/fix

Add `=` in the documentation to all CLI flags that receive arguments, e.g.

```
--load_path=https://olmo-checkpoints.org/ai2-llm/olmo-small/w1r5xfzt/step1000-unsharded
```

**Comment by 2015aroras** [comment]
Thank you for pointing out this issue in the README! As you noted, arguments of `scripts/train.py` need to passed in the form `--arg=value`. A PR with the README fix is welcome.
