### ISSUE TITLE
Criteria for Selecting acc vs. len_norm Metrics

### ISSUE THREAD

**Issue by mathfinder** [allenai/OLMo#713]
### ❓ The question

What determines whether a metric uses acc or len_norm? It seems the only difference between them is whether the score for the continuation is divided by the number of tokens.

**Comment by dirkgr** [comment]
Maybe @OyvindTafjord can answer this, but I think the answer is that this is tuned for every dataset to produce the best possible numbers. Check https://www.semanticscholar.org/paper/OLMES%3A-A-Standard-for-Language-Model-Evaluations-Gu-Tafjord/c689c37c5367abe4790bff402c1d54944ae73b2a?utm_source=direct_link for details.
