### ISSUE TITLE
How to inspect training data in a particular batch?

### ISSUE THREAD

**Issue by explanare** [allenai/OLMo#763]
### ❓ The question

I would like to inspect training data in a particular batch as described [here](https://pypi.org/project/ai2-olmo/#Inspecting%20training%20data). I also noticed that there is another script [inspect_train_data.py](https://github.com/allenai/OLMo/blob/main/scripts/inspect_train_data.py) doing similar things. Unfortunately, both scripts require the `global_indices.npy` file, which is no longer available on the server, e.g., for the OLMo-7B model, [https://olmo-checkpoints.org/ai2-llm/olmo-medium/wvc30anm/train_data/global_indices.npy](https://olmo-checkpoints.org/ai2-llm/olmo-medium/wvc30anm/train_data/global_indices.npy) is no longer accessible.

Is there a new URL where we could download these `global_indices.npy` files for the pre-trained models, or do we have to rebuild the `global_indices.npy` locally? Also, are there any tools to sample training data for a particular batch without downloading the entire training corpus?

Thanks in advance!

**Comment by aman-17** [comment]
Hello @explanare, we have taken down these links since we have released our latest OLMo model which performs better than this version. For the latest release(OLMo-2), you have to build the  `global_indices.npy` locally. To sample training data, you can try filtering techniques. Let me know if you need anything.

**Comment by explanare** [comment]
@aman-17 Thanks for confirming! Will try to build the index locally.

Closing this issue for now.

**Comment by aman-17** [comment]
Hey @explanare, we have restored `global_indices.npy` file, feel free to reopen the issue if you need anything.

**Comment by explanare** [comment]
@aman-17 For OLMo-7B, it seems that the global_indices.npy file is only restored for the first epoch. Would it be possible to restore the index for the second epoch as well, i.e., the one [here](https://pypi.org/project/ai2-olmo/0.5.1/) https://olmo-checkpoints.org/ai2-llm/olmo-medium/wd2gxrza/train_data/global_indices.npy? We are able to reconstruct the index locally, but we would like to verify the correctness of the order.

**Comment by aman-17** [comment]
Hey @explanare Hey @explanare, unfortunately, we don’t have these. I created global_indices by using a deprecated script from the repository and restoring it.
