### ISSUE TITLE
Ensuring Data Order Tracking for Reproducibility

### ISSUE THREAD

**Issue by IanMagnusson** [allenai/OLMo#95]
### 🚀 The feature, motivation and pitch

Yesterday we spoke about where responsibility for data order lives between the llm-model and llm-data workstreams. I thought it might be good to start an issue here where we can figure out who and how we should ensure that future work can reproduce our exact pretraining data order.

Use cases:

- It should be clear exactly what tokens a given checkpoint has trained on, so we can ask if a model has seen a specific thing and how long ago it has seen that thing.
- It should be possible to recreate the same order of documents using a different tokenizer to allow other research to compare to ours.

Proposed features:

- Track which document IDs are in each concatenated example and which examples are in each batch
- Have dataloaders that queue up data across devices and nodes such that sequence of document IDs is always the same, even if the boundaries between batches change

Proposed method:

- When using `j * k` dataloaders, `dl_i` , across `j`  nodes and `k` devices, each data loader should sample from `n` documents of the pretraining corpus, `doc_i`, with a stride of `j*k`
- For example if `j=1`  and `k=2` , `dl_0[0] == doc_0` and `dl_1[0] == doc_1` while `dl_0[1] == doc_2` and `dl_1[1] == doc_3`
- Finally during training, the model will log the doc ids and associated spans in each concatenated example, and examples will be logged per batch. A rough example might be, `{batch_0 : [ [ (doc_0, (start_tok_idx, end_tok_idx)), ...], [(doc_42, (start_tok_idx, end_tok_idx)),...]]}`

Let me know what I can do to help support this and coordinate responsibility between llm-model and llm-data.

### Alternatives

A simple though reduced alternative is to just record the tokens that are trained on without any further changes.

While this supports the ability to see what a given checkpoint has seen and when it has seen it, this may make it difficult to recover batch and document boundaries or to reproduce this data order in a different tokenizer.

Also if we don’t ensure that data order is invariant to number of nodes and devices, it we may accidentally produce different training orders across different runs. Additionally it may be difficult for people using our codebase to reproduce our data order if they don’t have the same number of nodes and devices.

**Comment by dumitrac** [comment]
Marking the items prior to Feb 29th as "closed".
